custom:
  swagger:
    enable: true #是否启用swagger文档
  log:
    path: D:/logback/${spring.application.name}/${spring.profiles.active}
  token: 
      userClaim: userInfo
      survivalTime: 7200000
      secret: BD12@6$133a
    
spring:
  application:
    name: szedu
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/visa?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

    
server:
  port: 8080
