custom:
  swagger:
    enable: true #是否启用swagger文档
  log:
    path: D:/logback/${spring.application.name}/${spring.profiles.active}
  token:
      cache:
        initialCapacity: 500 #token缓存初始大小
        maximumSize: 100000 #token缓存的最大大小
        expireAfterAccessWithMinutes: 30 #最后一次访问后间隔多少分钟失效
      userClaim: userInfo
      survivalTime: 7200000
      secret: BD12@6$133a
      ingoreTokenUrls: /backRoleConsole/loginBackUser,/backRoleConsole/registBackUser,/swagger-ui.html#/*,/swagger-ui.html  #忽略检查token的URL
    
spring:
  application:
    name: szedu
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/visa?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    initialization-mode: always
    data : classpath:data.sql
    sql-script-encoding : utf-8
  main:
      allow-bean-definition-overriding: true

fengqiao:
  reqURL : http://bsp-oisp.sf-express.com/bsp-oisp/sfexpressService
  clientCode: HYTXGJLX
  checkWord: x5ZF2i6EZ7JG8vASyjyuTCt7MA6mmcH8

file:
  uploadFolder: D:/ #文件上传目录(window是d/e/f盘， linux是/)（注意Linux和Windows上的目录结构不同）
  imagePath: upload/ #文件保存路径(文件存在具体的文件夹的路径)
  staticAccessPath: /upload/**  #静态资源对外暴露的访问路径(访问图片的路径)
  uri: /upload/ #浏览器访问

    
server:
  port: 8080
